### ISSUE TITLE
Alternative interfaces?

### ISSUE THREAD

**Issue by sje30** [NeurodataWithoutBorders/specification#4]
Any likelihood of seeing packages for R or Julia to read/write the NWB format?  I have some MEA data in HDF5 format that could be added if you are looking for more test cases.  See http://gigascience.biomedcentral.com/articles/10.1186/2047-217X-3-3

**Comment by jeffteeters** [comment]
Probably not soon.  There is not yet a dedicated read API for the NWB format in any language.  The goal was to have the format simple enough to allow reading using just the HDF5 API.    For the write API, if the existing Python write API can be called from R or Julia, then maybe that could be adapted to work for those languages.  AFAIK, there are no plans to create a write API entirely in R or Julia.

**Comment by sje30** [comment]
Thanks.  There is fairly good interop with python, esp from Julia, so
reusing python would be pragmatic.

> Probably not soon.  There is not yet a dedicated read API for the NWB format in any language.  The goal was to have the format simple enough to allow reading using just the HDF5 API.    For the write API, if the existing Python write API can be called from R or Julia, then maybe that could be adapted to work for those languages.  AFAIK, there are no plans to create a write API entirely in R or Julia.
